/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillGamesRouteImport } from './routes/skill-games'
import { Route as LaserTagRouteImport } from './routes/laser-tag'
import { Route as GoKartsRouteImport } from './routes/go-karts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SkillGamesRoute = SkillGamesRouteImport.update({
  id: '/skill-games',
  path: '/skill-games',
  getParentRoute: () => rootRouteImport,
} as any)
const LaserTagRoute = LaserTagRouteImport.update({
  id: '/laser-tag',
  path: '/laser-tag',
  getParentRoute: () => rootRouteImport,
} as any)
const GoKartsRoute = GoKartsRouteImport.update({
  id: '/go-karts',
  path: '/go-karts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/go-karts': typeof GoKartsRoute
  '/laser-tag': typeof LaserTagRoute
  '/skill-games': typeof SkillGamesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/go-karts': typeof GoKartsRoute
  '/laser-tag': typeof LaserTagRoute
  '/skill-games': typeof SkillGamesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/go-karts': typeof GoKartsRoute
  '/laser-tag': typeof LaserTagRoute
  '/skill-games': typeof SkillGamesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/go-karts'
    | '/laser-tag'
    | '/skill-games'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/go-karts' | '/laser-tag' | '/skill-games'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/go-karts'
    | '/laser-tag'
    | '/skill-games'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GoKartsRoute: typeof GoKartsRoute
  LaserTagRoute: typeof LaserTagRoute
  SkillGamesRoute: typeof SkillGamesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-games': {
      id: '/skill-games'
      path: '/skill-games'
      fullPath: '/skill-games'
      preLoaderRoute: typeof SkillGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laser-tag': {
      id: '/laser-tag'
      path: '/laser-tag'
      fullPath: '/laser-tag'
      preLoaderRoute: typeof LaserTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-karts': {
      id: '/go-karts'
      path: '/go-karts'
      fullPath: '/go-karts'
      preLoaderRoute: typeof GoKartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GoKartsRoute: GoKartsRoute,
  LaserTagRoute: LaserTagRoute,
  SkillGamesRoute: SkillGamesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
